language: node_js
node_js:
  - 0.6
notifications:
  webhooks: http://bjb.io:7076
  irc:
    - "irc.mozilla.org#badges"
  email:
    recipients:
      - openbadges+ci@mozilla.com
before_script:
  - cp lib/environments/local-dist.js lib/environments/local.js
  - mysql -e 'create database openbadges;'
  - mysql -e 'create database test_openbadges;'
  - mysql -uroot -e "grant all on openbadges.* to 'badgemaker'@'localhost' identified by 'secret'"
  - mysql -uroot -e "grant all on test_openbadges.* to 'badgemaker'@'localhost' identified by 'secret'"
  - node app.js &
script:
  - npm test
  - phantomjs static/test/phantom-qunit.js http://localhost:8888/test/
  - phantomjs static/test/phantom-qunit.js http://localhost:8888/test/badge-accept/
